// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.status_type */
enum StatusType {
  to_do = 'to_do',
  in_progress = 'in_progress',
  done = 'done',
};

export default StatusType;
