// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type StatusType from './StatusType';
import type { UsersUserId } from './Users';

/** Identifier type for public.task */
export type TaskTaskId = number & { __brand: 'TaskTaskId' };

/** Represents the table public.task */
export default interface Task {
  task_id: TaskTaskId;

  task_title: string;

  task_description: string | null;

  task_status: StatusType;

  user_id: UsersUserId | null;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.task */
export interface TaskInitializer {
  /** Default value: nextval('task_task_id_seq'::regclass) */
  task_id?: TaskTaskId;

  task_title: string;

  task_description?: string | null;

  task_status: StatusType;

  user_id?: UsersUserId | null;

  /** Default value: now() */
  created_at?: Date | null;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.task */
export interface TaskMutator {
  task_id?: TaskTaskId;

  task_title?: string;

  task_description?: string | null;

  task_status?: StatusType;

  user_id?: UsersUserId | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}
