// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.user_role */
enum UserRole {
  admin = 'admin',
  user = 'user',
  guest = 'guest',
};

export default UserRole;
