// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type UserRole from './UserRole';

/** Identifier type for public.users */
export type UsersUserId = number & { __brand: 'UsersUserId' };

/** Represents the table public.users */
export default interface Users {
  user_id: UsersUserId;

  user_email: string;

  user_password: string;

  first_name: string | null;

  last_name: string | null;

  role: UserRole | null;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: nextval('users_user_id_seq'::regclass) */
  user_id?: UsersUserId;

  user_email: string;

  user_password: string;

  first_name?: string | null;

  last_name?: string | null;

  /** Default value: 'user'::user_role */
  role?: UserRole | null;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  user_id?: UsersUserId;

  user_email?: string;

  user_password?: string;

  first_name?: string | null;

  last_name?: string | null;

  role?: UserRole | null;
}
