// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table task {
  task_id integer [primary key]
  task_title text
  task_description text 
  status_id integer

}

Table status {
  status_id integer [primary key]
  status_name text
}



/*
< one-to-many.
> many-to-one.
- one-to-one.
<> many-to-many.   
*/
Ref: status.status_id < task.status_id //one-to-many



