// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.task_status */
export type TaskStatusStatusId = number & { __brand: 'TaskStatusStatusId' };

/** Represents the table public.task_status */
export default interface TaskStatus {
  status_id: TaskStatusStatusId;

  status_name: string;
}

/** Represents the initializer for the table public.task_status */
export interface TaskStatusInitializer {
  /** Default value: nextval('task_status_status_id_seq'::regclass) */
  status_id?: TaskStatusStatusId;

  status_name: string;
}

/** Represents the mutator for the table public.task_status */
export interface TaskStatusMutator {
  status_id?: TaskStatusStatusId;

  status_name?: string;
}
