// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TaskStatusStatusId } from './TaskStatus';

/** Identifier type for public.task */
export type TaskTaskId = number & { __brand: 'TaskTaskId' };

/** Represents the table public.task */
export default interface Task {
  task_id: TaskTaskId;

  task_title: string;

  task_description: string | null;

  status_id: TaskStatusStatusId;
}

/** Represents the initializer for the table public.task */
export interface TaskInitializer {
  /** Default value: nextval('task_task_id_seq'::regclass) */
  task_id?: TaskTaskId;

  task_title: string;

  task_description?: string | null;

  status_id: TaskStatusStatusId;
}

/** Represents the mutator for the table public.task */
export interface TaskMutator {
  task_id?: TaskTaskId;

  task_title?: string;

  task_description?: string | null;

  status_id?: TaskStatusStatusId;
}
